/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAtividadesRouteImport } from './routes/_authenticated/atividades'
import { Route as AuthenticatedCampanhasRouteImport } from './routes/_authenticated/campanhas'
import { Route as AuthenticatedContratosRouteImport } from './routes/_authenticated/contratos'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedEquipaRouteImport } from './routes/_authenticated/equipa'
import { Route as AuthenticatedFollowupsRouteImport } from './routes/_authenticated/followups'
import { Route as AuthenticatedPropostasRouteImport } from './routes/_authenticated/propostas'
import { Route as AuthenticatedVisitasRouteImport } from './routes/_authenticated/visitas'
import { Route as AuthenticatedClientesIndexRouteImport } from './routes/_authenticated/clientes.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAtividadesRoute = AuthenticatedAtividadesRouteImport.update({
  id: '/atividades',
  path: '/atividades',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCampanhasRoute = AuthenticatedCampanhasRouteImport.update({
  id: '/campanhas',
  path: '/campanhas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContratosRoute = AuthenticatedContratosRouteImport.update({
  id: '/contratos',
  path: '/contratos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEquipaRoute = AuthenticatedEquipaRouteImport.update({
  id: '/equipa',
  path: '/equipa',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFollowupsRoute = AuthenticatedFollowupsRouteImport.update({
  id: '/followups',
  path: '/followups',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPropostasRoute = AuthenticatedPropostasRouteImport.update({
  id: '/propostas',
  path: '/propostas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVisitasRoute = AuthenticatedVisitasRouteImport.update({
  id: '/visitas',
  path: '/visitas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientesIndexRoute =
  AuthenticatedClientesIndexRouteImport.update({
    id: '/clientes/',
    path: '/clientes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/atividades': typeof AuthenticatedAtividadesRoute
  '/campanhas': typeof AuthenticatedCampanhasRoute
  '/contratos': typeof AuthenticatedContratosRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/equipa': typeof AuthenticatedEquipaRoute
  '/followups': typeof AuthenticatedFollowupsRoute
  '/propostas': typeof AuthenticatedPropostasRoute
  '/visitas': typeof AuthenticatedVisitasRoute
  '/clientes/': typeof AuthenticatedClientesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/atividades': typeof AuthenticatedAtividadesRoute
  '/campanhas': typeof AuthenticatedCampanhasRoute
  '/contratos': typeof AuthenticatedContratosRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/equipa': typeof AuthenticatedEquipaRoute
  '/followups': typeof AuthenticatedFollowupsRoute
  '/propostas': typeof AuthenticatedPropostasRoute
  '/visitas': typeof AuthenticatedVisitasRoute
  '/clientes': typeof AuthenticatedClientesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/atividades': typeof AuthenticatedAtividadesRoute
  '/_authenticated/campanhas': typeof AuthenticatedCampanhasRoute
  '/_authenticated/contratos': typeof AuthenticatedContratosRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/equipa': typeof AuthenticatedEquipaRoute
  '/_authenticated/followups': typeof AuthenticatedFollowupsRoute
  '/_authenticated/propostas': typeof AuthenticatedPropostasRoute
  '/_authenticated/visitas': typeof AuthenticatedVisitasRoute
  '/_authenticated/clientes/': typeof AuthenticatedClientesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/atividades'
    | '/campanhas'
    | '/contratos'
    | '/dashboard'
    | '/equipa'
    | '/followups'
    | '/propostas'
    | '/visitas'
    | '/clientes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/atividades'
    | '/campanhas'
    | '/contratos'
    | '/dashboard'
    | '/equipa'
    | '/followups'
    | '/propostas'
    | '/visitas'
    | '/clientes'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/atividades'
    | '/_authenticated/campanhas'
    | '/_authenticated/contratos'
    | '/_authenticated/dashboard'
    | '/_authenticated/equipa'
    | '/_authenticated/followups'
    | '/_authenticated/propostas'
    | '/_authenticated/visitas'
    | '/_authenticated/clientes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/atividades': {
      id: '/_authenticated/atividades'
      path: '/atividades'
      fullPath: '/atividades'
      preLoaderRoute: typeof AuthenticatedAtividadesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/campanhas': {
      id: '/_authenticated/campanhas'
      path: '/campanhas'
      fullPath: '/campanhas'
      preLoaderRoute: typeof AuthenticatedCampanhasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contratos': {
      id: '/_authenticated/contratos'
      path: '/contratos'
      fullPath: '/contratos'
      preLoaderRoute: typeof AuthenticatedContratosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/equipa': {
      id: '/_authenticated/equipa'
      path: '/equipa'
      fullPath: '/equipa'
      preLoaderRoute: typeof AuthenticatedEquipaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/followups': {
      id: '/_authenticated/followups'
      path: '/followups'
      fullPath: '/followups'
      preLoaderRoute: typeof AuthenticatedFollowupsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/propostas': {
      id: '/_authenticated/propostas'
      path: '/propostas'
      fullPath: '/propostas'
      preLoaderRoute: typeof AuthenticatedPropostasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/visitas': {
      id: '/_authenticated/visitas'
      path: '/visitas'
      fullPath: '/visitas'
      preLoaderRoute: typeof AuthenticatedVisitasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clientes/': {
      id: '/_authenticated/clientes/'
      path: '/clientes'
      fullPath: '/clientes/'
      preLoaderRoute: typeof AuthenticatedClientesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAtividadesRoute: typeof AuthenticatedAtividadesRoute
  AuthenticatedCampanhasRoute: typeof AuthenticatedCampanhasRoute
  AuthenticatedContratosRoute: typeof AuthenticatedContratosRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEquipaRoute: typeof AuthenticatedEquipaRoute
  AuthenticatedFollowupsRoute: typeof AuthenticatedFollowupsRoute
  AuthenticatedPropostasRoute: typeof AuthenticatedPropostasRoute
  AuthenticatedVisitasRoute: typeof AuthenticatedVisitasRoute
  AuthenticatedClientesIndexRoute: typeof AuthenticatedClientesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAtividadesRoute: AuthenticatedAtividadesRoute,
  AuthenticatedCampanhasRoute: AuthenticatedCampanhasRoute,
  AuthenticatedContratosRoute: AuthenticatedContratosRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEquipaRoute: AuthenticatedEquipaRoute,
  AuthenticatedFollowupsRoute: AuthenticatedFollowupsRoute,
  AuthenticatedPropostasRoute: AuthenticatedPropostasRoute,
  AuthenticatedVisitasRoute: AuthenticatedVisitasRoute,
  AuthenticatedClientesIndexRoute: AuthenticatedClientesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
